# Generated by Django 4.0.4 on 2022-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_signup_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='signup',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
